[project]
name = "mdscl"
version = "0.1.0"
description = "MDS-CL coursework environment"
readme = "README.md"
authors = [
    { name = "youralmight", email = "youralmight@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.11.1",
    "otter-grader>=7.0.0",
]

[tool.uv]
package = false
