[project]
name = "mdscl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "youralmight", email = "youralmight@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.11.1",
    "otter-grader>=7.0.0",
]

[project.scripts]
mdscl = "mdscl:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = "admin/python/src"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
